# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='s_name',
            field=models.CharField(max_length=20),
        ),
    ]
