# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_current',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock_current',
            name='shcode',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
