# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_current',
            name='change',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock_current',
            name='diff',
            field=models.FloatField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock_current',
            name='price',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock_current',
            name='sign',
            field=models.IntegerField(max_length=1),
        ),
    ]
