# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0002_auto_20160209_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_current',
            old_name='avg',
            new_name='avgp',
        ),
        migrations.RenameField(
            model_name='stock_current',
            old_name='open',
            new_name='openp',
        ),
        migrations.RenameField(
            model_name='stock_current',
            old_name='value',
            new_name='valuep',
        ),
    ]
