# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0002_auto_20160311_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_current',
            name='avgp',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock_current',
            name='dnlmtprice',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock_current',
            name='high',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock_current',
            name='jnilvolume',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='stock_current',
            name='low',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock_current',
            name='openp',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock_current',
            name='recprice',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock_current',
            name='uplmtprice',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock_current',
            name='valuep',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='stock_current',
            name='volume',
            field=models.IntegerField(max_length=12),
        ),
    ]
