# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0005_auto_20160209_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_current',
            name='volumediff',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
