# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0007_auto_20160209_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock2',
            name='s_close',
        ),
        migrations.RemoveField(
            model_name='stock2',
            name='s_date',
        ),
        migrations.RemoveField(
            model_name='stock2',
            name='s_open',
        ),
    ]
