# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0003_auto_20160312_1614'),
        ('accounts', '0003_auto_20160316_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sdata.Stock_current'),
        ),
    ]
