# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0003_auto_20160312_1614'),
        ('accounts', '0004_userprofile_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stock',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stock',
            field=models.ManyToManyField(blank=True, null=True, to='sdata.Stock_current'),
        ),
    ]
