# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0001_initial'),
        ('blog', '0006_auto_20160214_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sdata.Stock_current'),
        ),
    ]
