# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_timeline_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='like',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
